# Generated by Django 5.0 on 2023-12-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_user_management', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('0', 'None'), ('1', 'View Reports'), ('2', 'Create/Modify'), ('3', 'Both')], max_length=1)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console_user_management.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console_user_management.role')),
            ],
        ),
    ]
