# Generated by Django 5.0 on 2023-12-31 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_user_management', '0003_permission_rolepermissionassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermissionassignment',
            name='permission_level',
            field=models.CharField(choices=[('0', 'None'), ('1', 'View Reports'), ('2', 'Create/Modify')], max_length=1),
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console_user_management.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
